from . import hr_employee
from . import as_res_partner
from . import hr_payslip
from . import hr_afp
from . import hr_contract_type
from . import hr_indicadores_previsionales
from . import hr_isapre
from . import hr_payslip_run
from . import hr_payslip_employees
from . import hr_salary_rule
from . import hr_type_employee
from . import hr_mutualidad
from . import hr_ccaf
from . import hr_contract
from . import hr_seguro_complementario
from . import hr_holidays
from . import hr_apv
from . import hr_contribution_register 
from . import as_resource_calendar
from . import as_company
from . import as_articulo_codigo
from . import amount_to_text_es
from . import as_employer
from . import as_excel_txt
from . import hr_move_employee